#!/bin/bash

TESTFLAGS=''
[[ "$1" == "-b" ]] && TESTFLAGS='-b'

TESTDIR='./data'
TESTSIZE=(4 256 512 1024 4096 524288)

[[ ! -d $TESTDIR ]] && mkdir $TESTDIR

testfile=(${TESTDIR}/*)

for ts in "${TESTSIZE[@]}"; do
	fname="${TESTDIR}/data.${ts}.raw"
	[[ ! -f $fname ]] && dd bs=1024 count=$ts </dev/urandom >$fname 2>/dev/null
	testfile+=($fname)
done
sync

if [[ ! -d ./build ]]; then
	meson setup build
	cd build
	ninja
	cd ..
fi

TIMEFORMAT=%R
comptime=('compression')
decmtime=('decompression')
rapp=('compression ratio')
resul=('result')

for fname in "${testfile[@]}"; do
	fcmp="${fname}.hff"
	fdec="${fname}.dec"
	comptime+=($( { time cat "$fname" | ./build/huffman $TESTFLAGS -c > "$fcmp"; } 2>&1 ))
	if [ $? == 0 ]; then
		decmtime+=($( { time cat "$fcmp" | ./build/huffman $TESTFLAGS -d > "$fdec"; } 2>&1 ))
		if [ $? == 0 ]; then
			if [ "$(md5sum $fname | awk '{print $1}')" = "$(md5sum $fdec | awk '{print $1}')" ]; then
				resul+=("successfull")
				ssrc=$(stat -c %s ${fname})
				scom=$(stat -c %s ${fcmp})
				rapp+=($(awk -v o=$ssrc -v c=$scom 'BEGIN { printf "%.2f", (1 - c/o) * 100 }'))
			else
				rapp+=(-1)
				resul+=("fail")
			fi
		else
			rapp+=(-1)
			resul+=('err.decompression')
		fi
	else
		decmtime+=(-1)
		rapp+=(-1)
		resul+=('err.compression')
	fi
done

testfile=("file name" "${testfile[@]}")
for i in "${!testfile[@]}"; do
	echo -e "${testfile[i]}:${comptime[i]}s:${decmtime[i]}s:%${rapp[i]}:${resul[i]}"
done | column -t -s :

rm $TESTDIR/*.raw
rm $TESTDIR/*.hff
rm $TESTDIR/*.dec


